[package]
name = "h264"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "0.5.6"
memchr = "2.6.4"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "iterate_annex_b"
harness = false
