[package]
name = "encoders"
version = "0.1.0"
edition = "2021"

[features]
fdk_aac = []
x264 = ["x264-sys"]

[dependencies]
snafu = { version = "0.7.0", default-features = false }
x264-sys = { path = "../x264-sys", optional = true }
