[package]
name = "srt"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[features]
default = []
async = ["tokio"]

[dependencies]
libc = "0.2.71"
lazy_static = "1.4.0"
tokio = { version = "0.2.13", features = ["blocking", "macros", "io-util"], optional = true }
chrono = "0.4.19"
