[package]
name = "mpeg4"
version = "0.1.0"
authors = ["Christopher Brown <ccbrown112@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = ["core2/std"]

[dependencies]
byteorder = "1.3.4"
core2 = { version = "0.4.0", features = ["alloc"] }
