[package]
name = "rfc6381"
version = "0.1.0"
edition = "2018"

[features]
default = []
ffmpeg = ["dep:ffmpeg"]

[dependencies]
h264 = { path = "../h264" }
h265 = { path = "../h265" }
ffmpeg = { path = "../ffmpeg", features = ["avcodec"], optional = true }
