[package]
name = "mpeg2"
version = "0.1.0"
edition = "2018"

[features]
default = ["std"]
std = ["core2/std"]

[dependencies]
byteorder = { version = "1.3.4", default-features = false }
crc = "2.0.0"
core2 = { version = "0.4.0", features = ["alloc"] }
